In [1]:
import tensorflow as tf

tf.placeholder(dtype, shape=None, name=None)

In [2]:
a = tf.placeholder(tf.float32, shape=[3])
b = tf.constant([5, 5, 5], tf.float32)

In [3]:
c = a + b

In [5]:
with tf.Session() as sess:
    print(sess.run(c, feed_dict={a:[1,2,3]}))

[6. 7. 8.]


To feed multiple data points

In [6]:
list_of_values = [[1,2,3],[4,5,6]]
with tf.Session() as sess:
    for a_value in list_of_values:
        print(sess.run(c, feed_dict={a:a_value}))

[6. 7. 8.]
[ 9. 10. 11.]


To check if the tensor is feedable
tf.Graph.is_feedable(tensor)

**Lazy Loading Example**

Normal Loading

In [7]:
x = tf.Variable(10, name='x')
y = tf.Variable(20, name='y')
z = tf.add(x, y)

In [8]:
with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    for i in range(10):
        sess.run(z)


__Lazy Loading__